# Generated by Django 5.2.10 on 2026-02-01 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('individual', 'Individual'), ('ngo', 'NGO Partner')], default='individual', max_length=20),
        ),
    ]
