# Generated by Django 5.2.10 on 2026-01-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('furniture', 'Furniture'), ('books', 'Books'), ('electronics', 'Electronics'), ('clothes', 'Clothes'), ('utensils', 'Utensils')], max_length=20)),
                ('description', models.TextField()),
                ('condition_rating', models.IntegerField(default=5)),
                ('location', models.CharField(max_length=255)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
