# Generated by Django 5.2.10 on 2026-01-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='giver',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='item',
            name='condition_rating',
        ),
        migrations.RemoveField(
            model_name='item',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='item',
            name='location',
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('furniture', 'Furniture'), ('books', 'Books'), ('clothing', 'Clothing')], max_length=20),
        ),
    ]
