# Generated by Django 5.2.10 on 2026-01-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0004_swaprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_swapped',
            field=models.BooleanField(default=False),
        ),
    ]
