# Generated by Django 5.2.10 on 2026-01-31 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0005_item_is_swapped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('furniture', 'Furniture'), ('books', 'Books'), ('clothing', 'Clothing'), ('toys', 'Toys & Games'), ('kitchen', 'Kitchenware'), ('general', 'General / Other')], max_length=20),
        ),
    ]
