# Generated by Django 5.2.10 on 2026-02-01 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0002_alter_center_options_center_created_at_and_more'),
        ('exchange', '0007_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='swaprequest',
            name='meeting_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='centers.center'),
        ),
    ]
