# Generated by Django 5.2.10 on 2026-02-01 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0008_swaprequest_meeting_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='swaprequest',
            name='owner_agreed_location',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='swaprequest',
            name='sender_agreed_location',
            field=models.BooleanField(default=False),
        ),
    ]
