# Generated by Django 5.2.10 on 2026-02-01 06:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0002_alter_center_options_center_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='center',
            name='center_type',
        ),
        migrations.AlterField(
            model_name='center',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Contact number must be 10 digits')]),
        ),
    ]
